title: Jesse P Lesperance
subtitle: InfoSec Leader, Mentor, Advisor, Board Member, Community Organizer
description: >- # this means to ignore newlines until "baseurl:"
  Jesse P Lesperance a highly skilled leader in the Information Security space/community.

url: "https://lesperance.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Github
      url : https://github.com/jplesperance


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: jesse.webp
author: Jesse P Lesperance
author_bio: Visionary cybersecurity and DevOps leader with a proven ability to transform complex challenges into innovative solutions. A polymath with deep expertise across cloud security, application security, penetration testing, and compliance frameworks, Jesse thrives in high-impact environments, quickly mastering new technologies and driving strategic security initiatives. Known for his dynamic leadership, he has built and led multiple security departments, fostering a culture of collaboration and technical excellence.<br /><br />Jesse is a natural problem solver with a strategic mindset, always seeking to optimize security, performance, and operational efficiency. His ability to mentor and elevate teams, combined with a relentless drive for innovation, makes him an asset to any organization. Whether architecting secure cloud environments, leading white-hat hacking initiatives, or implementing zero-trust security models, Jesse consistently delivers critical results while fostering camaraderie and a shared commitment to security excellence.
author_email: jesse@lesperance.io
author_location: US
author_website_url: "https://lesperance.io"
typewrite-text: InfoSec Leader, Martial Artist, and Father
hero_cover_img:  sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: SentiLink
              company_logo: sentilink.png
              company_url: https://sentilink.com
              designation: Principal Security Architect
              description: 08/2021 - Present
              visibility: true
            - company_name: SF Bay Area InfraGard
              company_logo: infragard.jpeg
              company_url: https://sfbay-infragard.org
              designation: Board Member - Secretary
              description: 01/2022 - Present
              visibility: true
            - company_name: Evernote
              company_logo: evernote.jpeg
              company_url: https://evernote.com
              designation: Senior Security Architect
              description: 01/2018 - 08/2021
              visibility: true
            - company_name: eBay
              company_logo: ebay.png
              company_url: https://ebay.com
              designation: Senior Security Engineer
              description: 04/2016 - 12/2017
              visibility: true
            - company_name: Apixio
              company_logo: apixio.png
              company_url: https://apixio.com
              designation: Manager, DevOps
              description: 01/2015 - 04/2016
              visibility: true


# Education
author_education_details:
              - org_logo: cism.png
                org_name: ISACA
                org_url: https://isaca.org
                org_degree: Certified Information Security Manager
                description: 01/2021
                visibility: true
              - org_logo: oswp.png
                org_name: Offensive Security
                org_url: https://offensive-security.com
                org_degree: Offensive Security Wireless Professional
                description: 05/2019
                visibility: true
              - org_logo: ejpt.jpeg
                org_name: eLearnSecurity
                org_url: https://elearnsecurity.com
                org_degree: eLearnSecurity Junior Penetration Tester
                description: 04/2019
                visibility: true
              - org_logo: ccsp.png
                org_name: (ISC)2
                org_url: https://isc.com
                org_degree: Certified Cloud Security Professional
                description: 07/2017
                visibility: true
              - org_logo: cisa.png
                org_name: ISACA
                org_url: https://isaca.org
                org_degree: Certified Information System Auditor
                description: 09/2016
                visibility: true
              
                

# Projects
author_project_details:
              - project_thumbnail: shad0wbridge.png
                project_title: Shad0wBridge
                project_description: Command and Control system for penetration testing and red team events.
                project_url: https://github.com/jplesperance/Shad0wBridge
                visibility: true
              - project_thumbnail: redissniffer.png
                project_title: Redis Sniffer
                project_description: A Redis event capture and replay utility
                project_url: https://github.com/jplesperance/redissniffer
                visibility: true

# social links
twitter_username: jlesperance
github_username:  jplesperance
facebook_username: 
linkedin_username: jesseplesperance
behance_username: 
instagram_username: 
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 
hackthebox_profile: https://app.hackthebox.com/profile/425475

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: 

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
